### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by chewi** [vbouchaud/gsmlib#9]
Hello. I gather you're the (not so) new upstream but it looks as though the various distributions (except Debian?) haven't caught on. I suspect this is because they prefer to have an actual release available. Would it be possible to put one out? If nothing is known to be broken, this shouldn't be too much effort. If you do, I can ensure that this is applied on Gentoo. I come here from the FreeSWITCH project, who have been bundling gsmlib in their source tree, but would prefer to rely on distributions if it becomes more widely available.

**Comment by vbouchaud** [comment]
Hello,
Sorry it tooks me so long to answer, I kind of forgot about this project. Few years ago when I "cloned" it, it was to remove all warnings from compilation and to have my own work material for a personal project. Sadly, I didn't have enough time to finish it and I just let it be there.
For now, nothing is known to be broken and you can do what you want with the source code.
If you want to rely on some more recent updates, looks like https://github.com/comio/gsmlib might be what you look for.

**Comment by chewi** [comment]
No problem. Seems like you unintentionally became Debian's upstream then! @comio's fork is probably no more official than yours so I guess gsmlib is effectively homeless at this time. My attention has moved away from FreeSWITCH for the moment but I'll work something out if I return to it. Thanks.
